
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.ahash]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.4"
criteria = "safe-to-run"

[[exemptions.allocator-api2]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.anes]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.anstyle]]
version = "1.0.13"
criteria = "safe-to-run"

[[exemptions.async-trait]]
version = "0.1.89"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.bincode]]
version = "2.0.0-rc.3"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.10.0"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.19.1"
criteria = "safe-to-deploy"

[[exemptions.burn]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.burn-autodiff]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.burn-common]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.burn-core]]
version = "0.14.1"
criteria = "safe-to-deploy"

[[exemptions.burn-derive]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.burn-ndarray]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.burn-tensor]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.bytemuck]]
version = "1.24.0"
criteria = "safe-to-deploy"

[[exemptions.bytemuck_derive]]
version = "1.10.2"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-io]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-ll]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.clap]]
version = "4.5.54"
criteria = "safe-to-run"

[[exemptions.clap_builder]]
version = "4.5.54"
criteria = "safe-to-run"

[[exemptions.clap_lex]]
version = "0.7.6"
criteria = "safe-to-run"

[[exemptions.cobs]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.colored]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.critical-section]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.15"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.18"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.crunchy]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.cubecl-common]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "4.1.3"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek-derive]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.20.11"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.20.11"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.20.11"
criteria = "safe-to-deploy"

[[exemptions.data-encoding]]
version = "2.9.0"
criteria = "safe-to-deploy"

[[exemptions.defmt]]
version = "0.3.100"
criteria = "safe-to-deploy"

[[exemptions.defmt]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.defmt-macros]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.defmt-parser]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.10"
criteria = "safe-to-deploy"

[[exemptions.derive-new]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.document-features]]
version = "0.2.12"
criteria = "safe-to-deploy"

[[exemptions.ed25519]]
version = "2.2.3"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.embassy-executor]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.embassy-executor-macros]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.embassy-time]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.embassy-time-driver]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.embassy-time-queue-driver]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal-async]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-io]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-io]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.equivalent]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.14"
criteria = "safe-to-deploy"

[[exemptions.fiat-crypto]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.foldhash]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.7.1"
criteria = "safe-to-deploy"

[[exemptions.hash32]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.15.5"
criteria = "safe-to-deploy"

[[exemptions.heapless]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.ident_case]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.is-terminal]]
version = "0.4.17"
criteria = "safe-to-run"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.17"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.83"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.180"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.litrs]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.14"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.29"
criteria = "safe-to-deploy"

[[exemptions.lru]]
version = "0.12.5"
criteria = "safe-to-deploy"

[[exemptions.matrixmultiply]]
version = "0.3.10"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.6"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.nb]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.nb]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.ndarray]]
version = "0.16.1"
criteria = "safe-to-deploy"

[[exemptions.num-complex]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.num-integer]]
version = "0.1.46"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.5"
criteria = "safe-to-run"

[[exemptions.parking_lot]]
version = "0.12.5"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.12"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.pollster]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic-util]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error-attr2]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error2]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.105"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.43"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.rand_distr]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.rawpointer]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.rayon]]
version = "1.11.0"
criteria = "safe-to-deploy"

[[exemptions.rayon-core]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.18"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.12.2"
criteria = "safe-to-run"

[[exemptions.regex-automata]]
version = "0.4.13"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.8.8"
criteria = "safe-to-run"

[[exemptions.rustc_version]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.22"
criteria = "safe-to-deploy"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-run"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.27"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_bytes]]
version = "0.11.19"
criteria = "safe-to-deploy"

[[exemptions.serde_core]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.149"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.8"
criteria = "safe-to-deploy"

[[exemptions.signature]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.15.1"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.6.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.114"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.17"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.17"
criteria = "safe-to-deploy"

[[exemptions.thread-tree]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.tokio]]
version = "1.49.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.44"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.36"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.22"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.void]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.walkdir]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.106"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.106"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.106"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.106"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.83"
criteria = "safe-to-run"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.11"
criteria = "safe-to-run"

[[exemptions.windows-link]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.60.2"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.53.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.33"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.33"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.8.2"
criteria = "safe-to-deploy"

[[exemptions.zmij]]
version = "1.0.12"
criteria = "safe-to-deploy"
